-- ============================================================
--  بيانات متابعة الاستراتيجيات المؤسسية — من ملف الإدارة
--  43 جهة. آمن للتكرار: يحذف بذرة العرض القديمة ثم يُدرج،
--  ولا يدهس صفاً عدّلته لاحقاً (on conflict do nothing).
-- ============================================================
delete from public.perf_items
 where section = 'inststrat' and data->>'demo' = 'true';

insert into public.perf_items (section, id, ord, data) values
  ('inststrat','ins-01',1,'{"sector": "المالي والاقتصادي", "owner": "وزارة التجارة", "consultant": "فارس السحيباني", "phone": "555880622", "email": "Falsuhaibani@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-11-03", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-02',2,'{"sector": "المالي والاقتصادي", "owner": "وزارة المالية", "consultant": "فاطمة القحطاني", "phone": "538992773", "email": "FAlqahtani@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-03-30", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-03',3,'{"sector": "المالي والاقتصادي", "owner": "وزارة الاقتصاد والتخطيط", "consultant": "خالد الخثلان", "phone": "532251915", "email": "kalkhathlan@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-04-13", "docs": "✓", "docsState": "جزئي", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-04',4,'{"sector": "المالي والاقتصادي", "owner": "وزارة الاستثمار", "consultant": "رؤى الحماد", "phone": "534708766", "email": "ralhammad@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-10-03", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-05',5,'{"sector": "المالي والاقتصادي", "owner": "الهيئة السعودية للمواصفات والمقاييس", "consultant": "فارس السحيباني", "phone": "555880622", "email": "Falsuhaibani@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-10-03", "docs": "✓", "docsState": "مكتمل", "target": "Q2", "live": "مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-06',6,'{"sector": "المالي والاقتصادي", "owner": "الهيئة السعودية للملكية الفكرية", "consultant": "خالد الخثلان", "phone": "532251915", "email": "kalkhathlan@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-07',7,'{"sector": "المالي والاقتصادي", "owner": "المركز الوطني لنظم الموارد الحكومية", "consultant": "فاطمة القحطاني", "phone": "538992773", "email": "FAlqahtani@adaa.gov.sa", "rep": "", "meet": "تم", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-08',8,'{"sector": "المالي والاقتصادي", "owner": "هيئة كفاءة الإنفاق والمشروعات الحكومية", "consultant": "فاطمة القحطاني", "phone": "538992773", "email": "FAlqahtani@adaa.gov.sa", "rep": "", "meet": "لم يتم بعد", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-09',9,'{"sector": "المالي والاقتصادي", "owner": "الهيئة العامة للمنشآت الصغيرة والمتوسطة", "consultant": "فارس السحيباني", "phone": "555880622", "email": "Falsuhaibani@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-10',10,'{"sector": "البنية التحتية", "owner": "وزارة النقل والخدمات اللوجستية", "consultant": "عمر الظاهري/ندى العمير", "phone": "558810018", "email": "Oaldhairi@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "24/02/2026 and 9/4/2026", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-11',11,'{"sector": "البنية التحتية", "owner": "وزارة الاتصالات وتقنية المعلومات", "consultant": "ريما السكران", "phone": "506991963", "email": "ralsakran@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-12',12,'{"sector": "البنية التحتية", "owner": "وزارة البيئة والمياه والزراعة", "consultant": "ياسر بخاري", "phone": "566431131", "email": "ybukhari@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-09-04", "docs": "✓", "docsState": "مكتمل", "target": "Q4", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-13',13,'{"sector": "البنية التحتية", "owner": "وزارة الطاقة", "consultant": "لمى المبدل", "phone": "594407670", "email": "lmubaddel@adaa.gov.sa", "rep": "لم يُرسل بعد", "meet": "تم", "meetAt": "", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-14',14,'{"sector": "البنية التحتية", "owner": "وزارة الصناعة والثروة المعدنية", "consultant": "لمى المبدل", "phone": "594407670", "email": "lmubaddel@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-07-04", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-15',15,'{"sector": "البنية التحتية", "owner": "هيئة المحتوى المحلي والمشتريات الحكومية", "consultant": "عبدالعزيز العون", "phone": "545408502", "email": "Aalawn@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-16',16,'{"sector": "البنية التحتية", "owner": "المركز الوطني للتنمية الصناعية", "consultant": "لمى المبدل", "phone": "594407670", "email": "lmubaddel@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-17',17,'{"sector": "البنية التحتية", "owner": "الهيئة السعودية للمدن الصناعية ومناطق التفنية", "consultant": "لمى المبدل", "phone": "594407670", "email": "lmubaddel@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-18',18,'{"sector": "البنية التحتية", "owner": "الهيئة العامة للنقل", "consultant": "عمر الظاهري/ندى العمير", "phone": "558810018", "email": "lmubaddel@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-19',19,'{"sector": "البنية التحتية", "owner": "مدينة الملك عبدالعزيز للعلوم والتقنية", "consultant": "ريما السكران", "phone": "506991963", "email": "ralsakran@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-20',20,'{"sector": "البنية التحتية", "owner": "هيئة الحكومة الرقمية", "consultant": "ريما السكران", "phone": "506991963", "email": "ralsakran@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-21',21,'{"sector": "الخدمات الاجتماعية", "owner": "وزارة التعليم", "consultant": "خالد الجرف", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-06-04", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-22',22,'{"sector": "الخدمات الاجتماعية", "owner": "وزارة الصحة", "consultant": "عبدالرحمن الرميح", "phone": "566844358", "email": "aalrumayh@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-04-14", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-23',23,'{"sector": "الخدمات الاجتماعية", "owner": "وزارة الموارد البشرية والتنمية الاجتماعية", "consultant": "هيفاء التركي", "phone": "544397702", "email": "Halturki@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-02-25", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-24',24,'{"sector": "الخدمات الاجتماعية", "owner": "الهيئة العامة للغذاء والدواء", "consultant": "عبدالرحمن الرميح", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-04-14", "docs": "✓", "docsState": "مكتمل", "target": "Q2", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-25',25,'{"sector": "الخدمات الاجتماعية", "owner": "المركز الوطني لتنمية القطاع غير الربحي", "consultant": "خالد الجرف", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-26',26,'{"sector": "الخدمات الاجتماعية", "owner": "معهد الإدارة العامة", "consultant": "خالد الجرف", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✓", "docsState": "مكتمل", "target": "Q4", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-27',27,'{"sector": "الخدمات الاجتماعية", "owner": "هيئة تقويم التعليم والتدريب", "consultant": "خالد الجرف", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-28',28,'{"sector": "الخدمات الاجتماعية", "owner": "هيئة الهلال الأحمر السعودي", "consultant": "عبدالرحمن الرميح", "phone": "566844358", "email": "aalrumayh@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-29',29,'{"sector": "الخدمات الاجتماعية", "owner": "مركز الإقامة المميزة", "consultant": "هيفاء التركي", "phone": "544397702", "email": "Halturki@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-30',30,'{"sector": "الخدمات الاجتماعية", "owner": "الهيئة السعودية للتخصصات الصحية", "consultant": "عبدالرحمن الرميح", "phone": "566844358", "email": "aalrumayh@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-31',31,'{"sector": "الخدمات الاجتماعية", "owner": "المؤسسة العامة للتدريب التقني والمهني", "consultant": "خالد الجرف", "phone": "532330111", "email": "Kaljurf@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-32',32,'{"sector": "الشؤون الحكومية", "owner": "وزارة الثقافة", "consultant": "وعد الشدي", "phone": "533494847", "email": "walsheddi@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-33',33,'{"sector": "الشؤون الحكومية", "owner": "وزارة العدل", "consultant": "هشام بياري", "phone": "555568136", "email": "hbeyari@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-07-04", "docs": "✓", "docsState": "لايمكن قياسه", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-34',34,'{"sector": "الشؤون الحكومية", "owner": "وزارة الحج والعمرة", "consultant": "عبدالاله الفوزان", "phone": "558877708", "email": "Aalfawzan@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-35',35,'{"sector": "الشؤون الحكومية", "owner": "وزارة الرياضة", "consultant": "ثامر الضبيب", "phone": "568223337", "email": "taldhubaib@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✓", "docsState": "مكتمل", "target": "Q4", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-36',36,'{"sector": "الشؤون الحكومية", "owner": "وزارة السياحة", "consultant": "وعد الشدي", "phone": "533494847", "email": "walsheddi@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-04-16", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-37',37,'{"sector": "الشؤون الحكومية", "owner": "وزارة البلديات والإسكان", "consultant": "مشاعل الدايل", "phone": "545781667", "email": "Maldail@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "2026-02-17", "docs": "✗", "docsState": "", "target": "", "live": "", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-38',38,'{"sector": "الشؤون الحكومية", "owner": "وزارة الإعلام", "consultant": "وعد الشدي", "phone": "533494847", "email": "walsheddi@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "تم", "meetAt": "", "docs": "✓", "docsState": "مكتمل", "target": "Q3", "live": "غير مفعل", "phase": "Phase 1", "demo": false}'::jsonb),
  ('inststrat','ins-39',39,'{"sector": "الشؤون الحكومية", "owner": "الهيئة السعودية للسياحة", "consultant": "عبدالله البكر", "phone": "0582366380", "email": "Aalbakr@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-40',40,'{"sector": "الشؤون الحكومية", "owner": "الهيئة العامة للعقار", "consultant": "مشاعل الدايل", "phone": "545781667", "email": "Maldail@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-41',41,'{"sector": "الشؤون الحكومية", "owner": "الهيئة العامة للترفيه", "consultant": "وعد الشدي", "phone": "533494847", "email": "walsheddi@adaa.gov.sa", "rep": "تمت تسمية ممثل", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-42',42,'{"sector": "الشؤون الحكومية", "owner": "الهيئة العامة للعناية بشؤون المسجد الحرام والمسجد النبوي", "consultant": "هشام بياري", "phone": "555568136", "email": "hbeyari@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb),
  ('inststrat','ins-43',43,'{"sector": "الشؤون الحكومية", "owner": "الهيئة الملكية لمدينة مكة المكرمة والمشاعر المقدسة", "consultant": "هشام بياري", "phone": "555568136", "email": "hbeyari@adaa.gov.sa", "rep": "", "meet": "", "meetAt": "", "docs": "", "docsState": "", "target": "", "live": "", "phase": "Phase 2", "demo": false}'::jsonb)
on conflict (section, id) do nothing;

select count(*) as "صفوف المؤسسية" from public.perf_items where section='inststrat';
